#!/bin/sh
#update-mime-database /usr/share/mime
#update-desktop-database /usr/share/applications

template=$(xdg-user-dir TEMPLATES)

mv /opt/WeblocOpener/Template.webloc $template/Webloc\ link.webloc