/*
 * (C) Copyright 2019.  Eugene Zrazhevsky and others.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *     http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * Contributors:
 * Eugene Zrazhevsky <eugene.zrazhevsky@gmail.com>
 */

package com.github.benchdoos.weblocopener.gui.wrappers;

import com.github.benchdoos.weblocopener.core.Translation;
import com.github.benchdoos.weblocopener.gui.panels.CreateNewFilePanel;
import com.github.benchdoos.weblocopener.utils.FrameUtils;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

public class CreateNewFileFrameWrapper extends JFrame {
    private JPanel contentPane;
    private CreateNewFilePanel createPanel;

    public CreateNewFileFrameWrapper() {
        initGui();
        initListeners();
        createPanel.setParentWindow(this);
        getRootPane().setDefaultButton(createPanel.getOkButton());
    }

    private void initListeners() {
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                if (createPanel.getUrlTextField().getText().isEmpty()) {
                    FrameUtils.fillTextFieldWithClipboard(createPanel.getUrlTextField());
                }
                super.windowActivated(e);
            }

            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
            }
        });
    }

    private void initGui() {
        setLayout(new GridLayout());
        add(contentPane);

        setTitle(Translation.getTranslatedString("CreateNewFileBundle", "windowTitle"));


        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        pack();
        setResizable(false);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        createPanel = new CreateNewFilePanel();
        contentPane.add(createPanel.$$$getRootComponent$$$(), new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
