# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: WeblocOpener release build

on:
  push:
    branches: [ "master", "rc/*"]
  pull_request:
    branches: [ "master", "rc/*"]

jobs:
  collect-source-code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Archive Source Code
      run: |
        git archive --format=zip --output=source-code.zip HEAD
        tar -czf source-code.tar.gz source-code.zip
        echo current location: $PWD
        ls -a
      working-directory: ${{ github.workspace }}
    - name: Upload source-code.zip
      uses: actions/upload-artifact@v2
      with:
        name: source-code.zip
        path: ${{ github.workspace }}/source-code.zip
    - name: Upload source-code.tar.gz
      uses: actions/upload-artifact@v2
      with:
        name: source-code.tar.gz
        path: ${{ github.workspace }}/source-code.tar.gz


  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set Unique Build ID
      id: unique_id
      run: echo "BUILD_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
    - name: Branch name
      run: |
        echo running on branch ${GITHUB_REF##*/}
        echo running on branch: $(echo ${GITHUB_REF#refs/heads/})
      working-directory: ${{ github.workspace }}
    - name: Clone core
      uses: GuillaumeFalourd/clone-github-repo-action@v2.2
      with:
        owner: 'benchdoos'
        repository: 'weblocopenercore'
        access-token: ${{ secrets.WEBLOCOPENERCORE }}
        branch: ${GITHUB_REF##*/}
    - name: Build WeblocOpener core
      run: |
        cd weblocopenercore 
        ls -a
        mvn -B clean install -P enable-dev-mode,hide-ultimate-mode

    - name: Build WeblocOpener
      run: mvn -B clean package -P build-setup,build-deb,build-exe --file pom.xml

    - name: Upload WeblocOpener.deb
      uses: actions/upload-artifact@v2
      with:
        name: WeblocOpener.deb
        path: ${{ github.workspace }}/target/WeblocOpener.deb
    - name: Upload WeblocOpenerSetup.exe
      uses: actions/upload-artifact@v2
      with:
        name: WeblocOpenerSetup.exe
        path: ${{ github.workspace }}/target/WeblocOpenerSetup.exe


  create-release:
    runs-on: ubuntu-latest
    needs:
      - build
      - collect-source-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set Unique Build ID
        id: unique_id
        run: echo "BUILD_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
      - name: Download source-code.zip
        uses: actions/download-artifact@v2
        with:
          name: source-code.zip
          path: ${{ github.workspace }}
      - name: Download source-code.tar.gz
        uses: actions/download-artifact@v2
        with:
          name: source-code.tar.gz
          path: ${{ github.workspace }}
      - name: Download WeblocOpener.deb
        uses: actions/download-artifact@v2
        with:
          name: WeblocOpener.deb
          path: ${{ github.workspace }}
      - name: Download source-code.tar.gz
        uses: actions/download-artifact@v2
        with:
          name: WeblocOpenerSetup.exe
          path: ${{ github.workspace }}
      - name: Watching
        run: |
          echo directories:
          find . -type d -print
          echo files:
          find . -type f -print
      - name: Create Draft Release
        run: |
          echo current location: $PWD
          ls -a
          RELEASE_NAME=rc-${GITHUB_REF##*/}-build.$BUILD_ID
          RELEASE_TAG=${GITHUB_REF##*/}-build.$BUILD_ID
          echo Release name: $RELEASE_NAME
          gh release create $RELEASE_TAG WeblocOpener.deb WeblocOpenerSetup.exe source-code.tar.gz source-code.zip --title "Build release: $RELEASE_NAME" --notes "Build: $RELEASE_TAG" --draft
        env:
          GITHUB_TOKEN: ${{ secrets.WEBLOCOPENER_RELEASES }}


  # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  dependency-graph:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
